/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.ue.principal;

/**
 *
 * @author uestudiantes
 */
public class Escritorio extends javax.swing.JFrame {

    
    public Escritorio() {
        initComponents();
    }
    
    public static void main(String[] args){
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            @Override
            public void run(){
                new Escritorio().setVisible(true);
            }
        });
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCitas = new javax.swing.JMenu();
        menuDoctores = new javax.swing.JMenu();
        menuAgregarD = new javax.swing.JMenuItem();
        menuModD = new javax.swing.JMenuItem();
        menuPacientes = new javax.swing.JMenu();

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        menuCitas.setText("Citas");
        jMenuBar1.add(menuCitas);

        menuDoctores.setText("Doctores");

        menuAgregarD.setText("Agregar ");
        menuAgregarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarDActionPerformed(evt);
            }
        });
        menuDoctores.add(menuAgregarD);

        menuModD.setText("Modificar ");
        menuDoctores.add(menuModD);

        jMenuBar1.add(menuDoctores);

        menuPacientes.setText("Pacientes");
        jMenuBar1.add(menuPacientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarDActionPerformed
        
        SelecDoc selecdoc = new SelecDoc();
        Desktop.add(selecdoc);
        selecdoc.show();
        
    }//GEN-LAST:event_menuAgregarDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAgregarD;
    private javax.swing.JMenu menuCitas;
    private javax.swing.JMenu menuDoctores;
    private javax.swing.JMenuItem menuModD;
    private javax.swing.JMenu menuPacientes;
    // End of variables declaration//GEN-END:variables
}
