package co.edu.ue.principal;

import co.edu.ue.entities.Doctores;
import co.edu.ue.entities.Telefonos;
import co.edu.ue.model.DoctoresDao;
import co.edu.ue.model.TelefonosDao;



public class BuscarDoc extends javax.swing.JInternalFrame {

    
    public BuscarDoc() {
        initComponents();
    }
    public void clearFields(){
        txtBDoc.setText("");
        txtNombreM1.setText("");
        txtAppM1.setText("");
        txtApmM1.setText("");
        txtTel1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBDoc = new javax.swing.JTextField();
        labelBDoc = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbldoc = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        labelapp = new javax.swing.JLabel();
        lblapm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDocumentoM = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JLabel();
        txtAppM = new javax.swing.JLabel();
        txtApmM = new javax.swing.JLabel();
        txtNombreM1 = new javax.swing.JTextField();
        txtAppM1 = new javax.swing.JTextField();
        txtApmM1 = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTel = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();
        lblTipoTel = new javax.swing.JLabel();
        txtTipoTelM = new javax.swing.JLabel();
        cbxTipoTelM1 = new javax.swing.JComboBox<>();
        btnBorrar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        txtBDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBDocActionPerformed(evt);
            }
        });

        labelBDoc.setText("Documento:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbldoc.setText("Documento: ");

        lblName.setText("Nombre: ");

        labelapp.setText("Primer apellido:");

        lblapm.setText("Segundo apellido:");

        txtDocumentoM.setText("******");

        txtNombreM.setText("******");

        txtAppM.setText("******");

        txtApmM.setText("******");

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtTel.setText("******");

        lblTel.setText("Telefono:");

        lblTipoTel.setText("Tipo de telefono:");

        txtTipoTelM.setText("******");

        cbxTipoTelM1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "CELULAR", "FIJO" }));
        cbxTipoTelM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoTelM1ActionPerformed(evt);
            }
        });

        btnBorrar.setText("Dar de baja");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldoc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelapp)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(labelBDoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName)
                                            .addComponent(lblTel)
                                            .addComponent(lblapm)
                                            .addComponent(lblTipoTel))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtDocumentoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtApmM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                .addComponent(txtAppM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                                .addComponent(txtNombreM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                            .addComponent(txtTipoTelM))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxTipoTelM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAppM1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApmM1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnMod)
                        .addGap(30, 30, 30)
                        .addComponent(btnClear)
                        .addGap(34, 34, 34)
                        .addComponent(btnBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBDoc)
                    .addComponent(txtBDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldoc)
                    .addComponent(txtDocumentoM))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(txtNombreM))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelapp)
                    .addComponent(txtAppM)
                    .addComponent(txtAppM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapm, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApmM)
                    .addComponent(txtApmM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoTel)
                            .addComponent(txtTipoTelM)
                            .addComponent(cbxTipoTelM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTel)
                            .addComponent(txtTel)
                            .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnMod)
                    .addComponent(btnBorrar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBDocActionPerformed
        
    }//GEN-LAST:event_txtBDocActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        clearFields();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        DoctoresDao dao = new DoctoresDao();
        TelefonosDao daoTel = new TelefonosDao();
        Doctores doc = new Doctores(0, "", "", "");
        Telefonos tel = new Telefonos("", 0);
        
        doc = dao.buscarDoctor(Integer.parseInt(txtBDoc.getText()));
        tel = daoTel.buscarTelM(Integer.parseInt(txtBDoc.getText()));
        
        txtApmM.setText(doc.getApellido_materno());
        txtAppM.setText(doc.getApellido_paterno());
        txtNombreM.setText(doc.getNombre_med());
        txtDocumentoM.setText(String.valueOf(doc.getDocumento_med()));
        txtTel.setText(tel.getNumero());
        if(tel.getCategoria() == 1){
            txtTipoTelM.setText("CELULAR");
        }
        else if(tel.getCategoria() == 2){
            txtTipoTelM.setText("FIJO");
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        
        DoctoresDao dao = new DoctoresDao();
        TelefonosDao daoTel = new TelefonosDao();
        Doctores doctor = new Doctores(Integer.parseInt(txtBDoc.getText()),txtNombreM1.getText()
                ,txtAppM1.getText(),txtApmM1.getText());
        
        String telViejo = txtTel.getText();
        
        Telefonos telNuevo =  new Telefonos(txtTel1.getText(), cbxTipoTelM1.getSelectedIndex());
       
        dao.modificarDoctor(doctor);
        daoTel.modificarTel(telNuevo, telViejo);
        
        clearFields();
         
    }//GEN-LAST:event_btnModActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxTipoTelM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoTelM1ActionPerformed
        
    }//GEN-LAST:event_cbxTipoTelM1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        DoctoresDao dao = new DoctoresDao();
        TelefonosDao daoTel = new TelefonosDao();
        Telefonos tel;
        tel = daoTel.buscarTelM(Integer.parseInt(txtBDoc.getText()));
        String numero = tel.getNumero();
        daoTel.DarDeBajaTel(numero);
        
        dao.DarDeBajaD(Integer.parseInt(txtBDoc.getText()));
         
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cbxTipoTelM1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBDoc;
    private javax.swing.JLabel labelapp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTipoTel;
    private javax.swing.JLabel lblapm;
    private javax.swing.JLabel lbldoc;
    private javax.swing.JLabel txtApmM;
    private javax.swing.JTextField txtApmM1;
    private javax.swing.JLabel txtAppM;
    private javax.swing.JTextField txtAppM1;
    private javax.swing.JTextField txtBDoc;
    private javax.swing.JLabel txtDocumentoM;
    private javax.swing.JLabel txtNombreM;
    private javax.swing.JTextField txtNombreM1;
    private javax.swing.JLabel txtTel;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JLabel txtTipoTelM;
    // End of variables declaration//GEN-END:variables
}
