/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.ue.principal;

import co.edu.ue.entities.Doctores;
import co.edu.ue.model.DoctoresDao;

/**
 *
 * @author uestudiantes
 */
public class BuscarDoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarDoc
     */
    public BuscarDoc() {
        initComponents();
    }
    public void clearFields(){
        txtBDoc.setText("");
        txtNombreM1.setText("");
        txtAppM1.setText("");
        txtApmM1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBDoc = new javax.swing.JTextField();
        labelBDoc = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbldoc = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        labelapp = new javax.swing.JLabel();
        lblapm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDocumentoM = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JLabel();
        txtAppM = new javax.swing.JLabel();
        txtApmM = new javax.swing.JLabel();
        txtNombreM1 = new javax.swing.JTextField();
        txtAppM1 = new javax.swing.JTextField();
        txtApmM1 = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTel = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        txtBDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBDocActionPerformed(evt);
            }
        });

        labelBDoc.setText("Documento:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbldoc.setText("Documento: ");

        lblName.setText("Nombre: ");

        labelapp.setText("Primer apellido:");

        lblapm.setText("Segundo apellido:");

        txtDocumentoM.setText("******");

        txtNombreM.setText("******");

        txtAppM.setText("******");

        txtApmM.setText("******");

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtTel.setText("******");

        lblTel.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(labelBDoc)
                        .addGap(18, 18, 18)
                        .addComponent(txtBDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelapp)
                                            .addGap(13, 13, 13))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblapm)
                                    .addComponent(lbldoc)
                                    .addComponent(lblTel))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnMod)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumentoM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnClear)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApmM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAppM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtNombreM1)
                                    .addComponent(txtAppM1)
                                    .addComponent(txtApmM1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnCancelar)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBDoc)
                    .addComponent(txtBDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnBuscar)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldoc)
                    .addComponent(jLabel1)
                    .addComponent(txtDocumentoM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtNombreM)
                    .addComponent(txtNombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelapp)
                    .addComponent(txtAppM)
                    .addComponent(txtAppM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapm)
                    .addComponent(txtApmM)
                    .addComponent(txtApmM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel)
                    .addComponent(lblTel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnClear)
                    .addComponent(btnMod))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBDocActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DoctoresDao dao = new DoctoresDao();
        Doctores doc = new Doctores(0, "", "", "");
        
        doc = dao.buscarDoctor(Integer.parseInt(txtBDoc.getText()));
        
        txtApmM.setText(doc.getApellido_materno());
        txtAppM.setText(doc.getApellido_paterno());
        txtNombreM.setText(doc.getNombre_med());
        txtDocumentoM.setText(String.valueOf(doc.getDocumento_med()));
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
        Doctores doctor = new Doctores(Integer.parseInt(txtBDoc.getText()),txtNombreM1.getText()
                ,txtAppM1.getText(),txtApmM1.getText());
        DoctoresDao dao = new DoctoresDao();
        
        dao.modificarDoctor(doctor);
        
        
    }//GEN-LAST:event_btnModActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBDoc;
    private javax.swing.JLabel labelapp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblapm;
    private javax.swing.JLabel lbldoc;
    private javax.swing.JLabel txtApmM;
    private javax.swing.JTextField txtApmM1;
    private javax.swing.JLabel txtAppM;
    private javax.swing.JTextField txtAppM1;
    private javax.swing.JTextField txtBDoc;
    private javax.swing.JLabel txtDocumentoM;
    private javax.swing.JLabel txtNombreM;
    private javax.swing.JTextField txtNombreM1;
    private javax.swing.JLabel txtTel;
    private javax.swing.JTextField txtTel1;
    // End of variables declaration//GEN-END:variables
}
